name = "weather"
compatibility_date = "2025-07-01"

workers_dev = false
routes = [{ pattern = "weather.heyitsmejosh.com", custom_domain = true }]

[assets]
directory = "web"

[observability]
enabled = true
